name = "FuzzyClusteringSimilarity"
uuid = "edb9ae08-98fc-4535-bc7b-43b5fa0191ff"
authors = ["Ryan DeWolfe <ryandewolfe33@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
